package dev.sebastianb.icbm4fabric.client.model.entity.rocket;

import dev.sebastianb.icbm4fabric.entity.rocket.TaterRocketEntity;
import net.minecraft.client.model.ModelPart;
import net.minecraft.client.render.VertexConsumer;
import net.minecraft.client.render.entity.model.EntityModel;
import net.minecraft.client.util.math.MatrixStack;


/**
 * Autogenerated by BlockBench
 */
public class TaterRocketModel extends EntityModel<TaterRocketEntity> {
    private final ModelPart body;
    private final ModelPart walls;
    private final ModelPart wall4_r1;
    private final ModelPart wall3_r1;
    private final ModelPart wall2_r1;
    private final ModelPart wall1_r1;
    private final ModelPart fins;
    private final ModelPart fin1;
    private final ModelPart top_r1;
    private final ModelPart bottom_r1;
    private final ModelPart fin2;
    private final ModelPart top_r2;
    private final ModelPart bottom_r2;
    private final ModelPart fin3;
    private final ModelPart top_r3;
    private final ModelPart bottom_r3;
    private final ModelPart fin4;
    private final ModelPart top_r4;
    private final ModelPart bottom_r4;
    private final ModelPart nose;
    private final ModelPart base4_r1;
    private final ModelPart base3_r1;
    private final ModelPart base2_r1;
    private final ModelPart base1_r1;
    public TaterRocketModel() {
        textureWidth = 64;
        textureHeight = 64;
        body = new ModelPart(this);
        body.setPivot(0.0F, 24.0F, 0.0F);
        body.setTextureOffset(0, 0).addCuboid(-2.0F, -30.0F, -2.0F, 4.0F, 30.0F, 4.0F, 0.0F, false);

        walls = new ModelPart(this);
        walls.setPivot(0.0F, 0.0F, 0.0F);
        body.addChild(walls);


        wall4_r1 = new ModelPart(this);
        wall4_r1.setPivot(0.0F, -19.0F, 0.0F);
        walls.addChild(wall4_r1);
        setRotationAngle(wall4_r1, 0.0F, 0.0F, 0.0F);
        wall4_r1.setTextureOffset(24, 15).addCuboid(-2.9F, -8.3F, -2.0F, 1.0F, 27.0F, 4.0F, 0.0F, false);

        wall3_r1 = new ModelPart(this);
        wall3_r1.setPivot(0.0F, -19.0F, 0.0F);
        walls.addChild(wall3_r1);
        setRotationAngle(wall3_r1, 0.0F, 1.5708F, 0.0F);
        wall3_r1.setTextureOffset(34, 15).addCuboid(-2.9F, -8.3F, -2.0F, 1.0F, 27.0F, 4.0F, 0.0F, false);

        wall2_r1 = new ModelPart(this);
        wall2_r1.setPivot(0.0F, -19.0F, 0.0F);
        walls.addChild(wall2_r1);
        setRotationAngle(wall2_r1, -3.1416F, 0.0F, 3.1416F);
        wall2_r1.setTextureOffset(44, 15).addCuboid(-2.9F, -8.3F, -2.0F, 1.0F, 27.0F, 4.0F, 0.0F, false);

        wall1_r1 = new ModelPart(this);
        wall1_r1.setPivot(0.0F, -19.0F, 0.0F);
        walls.addChild(wall1_r1);
        setRotationAngle(wall1_r1, 0.0F, -1.5708F, 0.0F);
        wall1_r1.setTextureOffset(54, 15).addCuboid(-2.9F, -8.3F, -2.0F, 1.0F, 27.0F, 4.0F, 0.0F, false);

        fins = new ModelPart(this);
        fins.setPivot(4.6963F, -6.275F, 2.1213F);
        body.addChild(fins);


        fin1 = new ModelPart(this);
        fin1.setPivot(-4.6963F, 1.275F, -2.1213F);
        fins.addChild(fin1);


        top_r1 = new ModelPart(this);
        top_r1.setPivot(4.2426F, -3.0F, 4.2426F);
        fin1.addChild(top_r1);
        setRotationAngle(top_r1, 0.4859F, -0.6389F, -0.7287F);
        top_r1.setTextureOffset(54, 46).addCuboid(-4.55F, -8.15F, -0.5F, 4.0F, 9.0F, 1.0F, 0.0F, false);

        bottom_r1 = new ModelPart(this);
        bottom_r1.setPivot(0.0F, 0.0F, 0.0F);
        fin1.addChild(bottom_r1);
        setRotationAngle(bottom_r1, 0.0F, -0.7854F, 0.0F);
        bottom_r1.setTextureOffset(54, 56).addCuboid(2.0F, -2.0F, -0.5F, 4.0F, 7.0F, 1.0F, 0.0F, false);

        fin2 = new ModelPart(this);
        fin2.setPivot(-4.6963F, 1.275F, -2.1213F);
        fins.addChild(fin2);
        setRotationAngle(fin2, 0.0F, -1.5708F, 0.0F);


        top_r2 = new ModelPart(this);
        top_r2.setPivot(4.2426F, -3.0F, 4.2426F);
        fin2.addChild(top_r2);
        setRotationAngle(top_r2, 0.4859F, -0.6389F, -0.7287F);
        top_r2.setTextureOffset(44, 46).addCuboid(-4.55F, -8.15F, -0.5F, 4.0F, 9.0F, 1.0F, 0.0F, false);

        bottom_r2 = new ModelPart(this);
        bottom_r2.setPivot(0.0F, 0.0F, 0.0F);
        fin2.addChild(bottom_r2);
        setRotationAngle(bottom_r2, 0.0F, -0.7854F, 0.0F);
        bottom_r2.setTextureOffset(44, 56).addCuboid(2.0F, -2.0F, -0.5F, 4.0F, 7.0F, 1.0F, 0.0F, false);

        fin3 = new ModelPart(this);
        fin3.setPivot(-4.6963F, 1.275F, -2.1213F);
        fins.addChild(fin3);
        setRotationAngle(fin3, -3.1416F, 0.0F, 3.1416F);


        top_r3 = new ModelPart(this);
        top_r3.setPivot(4.2426F, -3.0F, 4.2426F);
        fin3.addChild(top_r3);
        setRotationAngle(top_r3, 0.4859F, -0.6389F, -0.7287F);
        top_r3.setTextureOffset(34, 46).addCuboid(-4.55F, -8.15F, -0.5F, 4.0F, 9.0F, 1.0F, 0.0F, false);

        bottom_r3 = new ModelPart(this);
        bottom_r3.setPivot(0.0F, 0.0F, 0.0F);
        fin3.addChild(bottom_r3);
        setRotationAngle(bottom_r3, 0.0F, -0.7854F, 0.0F);
        bottom_r3.setTextureOffset(34, 56).addCuboid(2.0F, -2.0F, -0.5F, 4.0F, 7.0F, 1.0F, 0.0F, false);

        fin4 = new ModelPart(this);
        fin4.setPivot(-4.6963F, 1.275F, -2.1213F);
        fins.addChild(fin4);
        setRotationAngle(fin4, 0.0F, 1.5708F, 0.0F);


        top_r4 = new ModelPart(this);
        top_r4.setPivot(4.2426F, -3.0F, 4.2426F);
        fin4.addChild(top_r4);
        setRotationAngle(top_r4, 0.4859F, -0.6389F, -0.7287F);
        top_r4.setTextureOffset(24, 46).addCuboid(-4.5F, -8.15F, -0.5F, 4.0F, 9.0F, 1.0F, 0.0F, false);

        bottom_r4 = new ModelPart(this);
        bottom_r4.setPivot(0.0F, 0.0F, 0.0F);
        fin4.addChild(bottom_r4);
        setRotationAngle(bottom_r4, 0.0F, -0.7854F, 0.0F);
        bottom_r4.setTextureOffset(24, 56).addCuboid(2.0F, -2.0F, -0.5F, 4.0F, 7.0F, 1.0F, 0.0F, false);

        nose = new ModelPart(this);
        nose.setPivot(0.0F, 0.0F, 0.0F);
        body.addChild(nose);
        nose.setTextureOffset(48, 0).addCuboid(-2.0F, -36.0F, -2.0F, 4.0F, 6.0F, 4.0F, 0.0F, false);
        nose.setTextureOffset(44, 4).addCuboid(-0.5F, -41.0F, -0.5F, 1.0F, 5.0F, 1.0F, 0.0F, false);

        base4_r1 = new ModelPart(this);
        base4_r1.setPivot(0.0F, -29.5F, 0.0F);
        nose.addChild(base4_r1);
        setRotationAngle(base4_r1, 0.0F, 0.0F, 0.3316F);
        base4_r1.setTextureOffset(24, 0).addCuboid(-2.05F, 0.0F, -2.0F, 1.0F, 3.0F, 4.0F, 0.0F, false);

        base3_r1 = new ModelPart(this);
        base3_r1.setPivot(0.0F, -29.5F, 0.0F);
        nose.addChild(base3_r1);
        setRotationAngle(base3_r1, 1.5708F, 1.2392F, 1.5708F);
        base3_r1.setTextureOffset(34, 0).addCuboid(-2.05F, 0.0F, -2.0F, 1.0F, 3.0F, 4.0F, 0.0F, false);

        base2_r1 = new ModelPart(this);
        base2_r1.setPivot(0.0F, -29.5F, 0.0F);
        nose.addChild(base2_r1);
        setRotationAngle(base2_r1, -3.1416F, 0.0F, 2.81F);
        base2_r1.setTextureOffset(24, 7).addCuboid(-2.05F, 0.0F, -2.0F, 1.0F, 3.0F, 4.0F, 0.0F, false);

        base1_r1 = new ModelPart(this);
        base1_r1.setPivot(0.0F, -29.5F, 0.0F);
        nose.addChild(base1_r1);
        setRotationAngle(base1_r1, -1.5708F, -1.2392F, 1.5708F);
        base1_r1.setTextureOffset(34, 7).addCuboid(-2.05F, 0.0F, -2.0F, 1.0F, 3.0F, 4.0F, 0.0F, false);
    }

    @Override
    public void setAngles(TaterRocketEntity entity, float limbAngle, float limbDistance, float animationProgress, float headYaw, float headPitch) {

    }

    @Override
    public void render(MatrixStack matrixStack, VertexConsumer buffer, int packedLight, int packedOverlay, float red, float green, float blue, float alpha){

        body.render(matrixStack, buffer, packedLight, packedOverlay);
    }
    public void setRotationAngle(ModelPart bone, float x, float y, float z) {
        bone.pitch = x;
        bone.yaw = y;
        bone.roll = z;
    }

}
